# https://taskfile.dev

version: '3'

tasks:
  default:
    - task: test
  test:
    sources:
      - 'lua/**/*.lua'
    cmds:
      - nvim --headless -c ":PlenaryBustedDirectory lua/tests/ {minimal_init = 'lua/tests/minimal_init.lua'}" -c ":qa!"
